name: MyWorkFlow

on: push

jobs:
   tests:
      runs-on: windows-latest
      steps:
         - name: npm install
           run: npm ci
         - name: run tests
           run: npm run test:AddToCart
