name: Workflow

on: push

jobs:
   tests:
      runs-on: windows-latest
      steps:
         - uses: browser-actions/setup-chrome@v1
         - uses: actions/checkout@v3
         - uses: actions/setup-node@v1
           with:
              node-version: 18
         - name: Cypress run
           uses: cypress-io/github-action@v5
         - name: npm install
           run: npm ci
         - name: run tests
           run: npm run test:AddToCart
